#!/bin/bash
#SBATCH --job-name=pC-rebuild
#SBATCH --account=amath
#SBATCH --partition=cpu-g2
#SBATCH --cpus-per-task=16
#SBATCH --mem=64G
#SBATCH --time=08:00:00
#SBATCH --array=0-1
#SBATCH --output=/gscratch/amath/simku22/logs/pC_rebuild_%A_%a.out
#SBATCH --error=/gscratch/amath/simku22/logs/pC_rebuild_%A_%a.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=simku22@uw.edu

set -euo pipefail
export PATH="$HOME/.elan/bin:$PATH"
# nvm node/npm for proofwidgets/widgetJsAll JS bundle build
export PATH="$HOME/.nvm/versions/node/v22.22.2/bin:$PATH"
export LEAN_CC=/usr/bin/gcc
TOOLCHAIN_DIR="$HOME/.elan/toolchains/leanprover--lean4---v4.27.0"
export LIBRARY_PATH="$TOOLCHAIN_DIR/lib:${LIBRARY_PATH:-}"

# lean-stat-learning-theory removed: incompatible with v4.27.0 (proofwidgets v0.0.98
# uses Lake.Hash.ofHashable which does not exist in Lake v4.27.0).
PROJECTS=(
    "formal-conjectures:FormalConjecturesForMathlib"
    "FormalBook:FormalBook"
)

ENTRY="${PROJECTS[$SLURM_ARRAY_TASK_ID]}"
PROJECT="${ENTRY%%:*}"
MODULE="${ENTRY##*:}"
PROJ_DIR="/gscratch/amath/simku22/TheoremSearch/formalized_graph/data/formalization_projects/$PROJECT"

echo "=== Pipeline C rebuild: $PROJECT ($MODULE) ==="
cd "$PROJ_DIR"
echo "leanprover/lean4:v4.27.0" > lean-toolchain

# lean-stat-learning-theory's lake-manifest.json was generated by a newer Lake that
# uses string names; Lake v4.27.0 requires Name identifiers and can't parse it.
# Delete it so Lake v4.27.0 regenerates the manifest in its own format.
if [ "$PROJECT" = "lean-stat-learning-theory" ] && [ -f lake-manifest.json ]; then
    echo "--- Removing stale lake-manifest.json (incompatible with v4.27.0 Lake) ---"
    rm -f lake-manifest.json
fi

# Fetch/update all dependency packages before SSD redirect so the redirect
# can capture every package directory (including proofwidgets).
echo "--- Running lake update ---"
lake update 2>&1 || true

# Redirect all build outputs to node-local SSD to avoid NFS olean loss on gscratch.
LOCAL_BASE="/tmp/proj-${PROJECT}-${SLURM_JOB_ID:-$$}"
mkdir -p "$LOCAL_BASE/build"

# Pre-seed proofwidgets JS bundle from a matching workspace:
#   formal-conjectures uses proofwidgets v0.0.85 (git rev c04225ee) = mathlib4_v427
#   FormalBook uses proofwidgets v0.0.84 (different rev) — falls back to npm via nvm
MATHLIB_V427_PW_BUILD="/gscratch/amath/simku22/TheoremSearch/formalized_graph_v2/data/mathlib4_v427/.lake/packages/proofwidgets/.lake/build"
if [ "$PROJECT" = "formal-conjectures" ] && [ -d "$MATHLIB_V427_PW_BUILD" ]; then
    mkdir -p "$LOCAL_BASE/packages/proofwidgets"
    cp -a "$MATHLIB_V427_PW_BUILD/." "$LOCAL_BASE/packages/proofwidgets/"
    echo "--- Pre-seeded proofwidgets v0.0.85 build from mathlib4_v427 ---"
fi

# Wipe stale build dirs and replace with SSD symlinks
mkdir -p .lake
rm -rf .lake/build
ln -sfn "$LOCAL_BASE/build" .lake/build

find .lake/packages -maxdepth 1 -mindepth 1 -type d 2>/dev/null | while read -r pkg_dir; do
    pkg_name=$(basename "$pkg_dir")
    mkdir -p "$LOCAL_BASE/packages/$pkg_name"
    mkdir -p "$pkg_dir/.lake"
    rm -rf "$pkg_dir/.lake/build"
    ln -sfn "$LOCAL_BASE/packages/$pkg_name" "$pkg_dir/.lake/build"
done

trap "echo '--- Syncing project build from SSD to gscratch ---'; \
      rm -f '$PROJ_DIR/.lake/build'; \
      [ -d '$LOCAL_BASE/build' ] && mv '$LOCAL_BASE/build' '$PROJ_DIR/.lake/build' || true; \
      find '$PROJ_DIR/.lake/packages' -maxdepth 1 -mindepth 1 -type d 2>/dev/null | while read -r pkg_dir; do \
          pkg_name=\$(basename \"\$pkg_dir\"); \
          rm -f \"\$pkg_dir/.lake/build\"; \
          [ -d '$LOCAL_BASE/packages/'\"\$pkg_name\" ] && mv '$LOCAL_BASE/packages/'\"\$pkg_name\" \"\$pkg_dir/.lake/build\" || true; \
      done" EXIT

lake build "$MODULE" 2>&1
ls -la ".lake/build/lib/lean/$MODULE.olean" 2>/dev/null && echo "SUCCESS" || echo "FAILED"
